spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # Redis 자동 설정 비활성화 (개발 환경)
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console


server:
  port: 8090
  servlet:
    encoding:
      charset: UTF-8
      force: true

jwt:
  secret: mySecretKey123456789012345678901234567890123456789012345678901234567890
  expiration:
    access: 3600000       # Access Token 유효 시간 (1시간)
    refresh: 2592000000   # Refresh Token 유효 시간 (30일)

logging:
  level:
    org.springframework.security: DEBUG
    fintech2.easypay: DEBUG