spring:
  application:
    name: easypay
  profiles:
    active: dev
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

#jwt:
#  expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG
    fintech2.easypay: DEBUG