spring:
  application:
    name: easypay
  profiles:
    active: dev
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  expiration: 86400000

# 외부 은행 API 설정
external:
  banking:
    api:
      base-url: https://api.banking.example.com
      timeout: 30000
      key: ${BANKING_API_KEY:test-api-key}

logging:
  level:
    org.springframework.security: DEBUG
    fintech2.easypay: DEBUG