name: EasyPay PR Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  JAVA_VERSION: '21'

jobs:
  # 테스트 및 빌드 (PR용)
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Run tests
      run: ./gradlew test
      
    - name: Build application
      run: ./gradlew build -x test
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: build/test-results/
        retention-days: 30

  # 코드 품질 검사 (PR용)
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Run SpotBugs
      run: ./gradlew spotbugsMain
      
    - name: Run PMD
      run: ./gradlew pmdMain
      
    - name: Upload SpotBugs results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: spotbugs-results
        path: build/reports/spotbugs/
        retention-days: 30
        
    - name: Upload PMD results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: pmd-results
        path: build/reports/pmd/
        retention-days: 30

  # PR 요약 알림
  pr-summary:
    runs-on: ubuntu-latest
    needs: [test-and-build, code-quality]
    if: github.event_name == 'pull_request'
    
    steps:
    - name: PR Summary
      run: |
        echo "✅ EasyPay PR Checks Completed!"
        echo "📊 Test Results: Available in artifacts"
        echo "🔍 Code Quality: SpotBugs & PMD results uploaded"
        echo "📝 Ready for code review!"
        echo "💡 Security scan will run on deployment or weekly" 